# Copyright 2023, Battelle Energy Alliance, LLC
nodes = [
    "attack_pattern",
    "campaign",
    "course_of_action",
    "grouping",
    "identity",
    "incident",
    "indicator",
    "infrastructure",
    "intrusion_set",
    "location",
    "to_maps_url",
    "malware",
    "malware_analysis",
    "note",
    "observed_data",
    "opinion",
    "report",
    "threat_actor",
    "tool",
    "vulnerability",
    "alternate_data_stream",
    "archive_ext",
    "artifact",
    "autonomous_system",
    "directory",
    "domain_name",
    "email_address",
    "email_mime_component",
    "email_message",
    "file",
    "http_request_ext",
    "icmp_ext",
    "ipv4_addr",
    "ipv6_addr",
    "mac_addr",
    "mutex",
    "ntfs_ext",
    "network_traffic",
    "pdf_ext",
    "process",
    "raster_image_ext",
    "socket_ext",
    "software",
    "tcp_ext",
    "unix_account_ext",
    "url",
    "user_account",
    "windows_pe_binary_ext",
    "windows_pe_optional_header_type",
    "windows_pe_section",
    "windows_process_ext",
    "windows_registry_key",
    "windows_registry_value_type",
    "windows_service_ext",
    "x509_certificate",
    "x509V3_extensions_type",
]

edges = [
    "creates",
    "deletes",
    "dynamic_analysis_of",
    "av_analysis_of",
    "located_at",
    "modifies",
    "reads",
    "related_to",
    "uses",
]

properties = [
    ("all", "id", "STRING"),
]

indexes = [
    ("all", "id", "UNIQUE_HASH_INDEX"),
]
