# Copyright 2023, Battelle Energy Alliance, LLC
import logging
from stix2 import Identity, ExtensionDefinition, MemoryStore

staticextensions = {
    "mitre": {
        "ext": {
            "created": "2022-07-06T15:34:22.474326Z",
            "created_by_ref": "identity--e769b29f-65d2-4cd3-9dbf-aed5609242af",
            "description": "Autogenerated " "extension " "definition",
            "extension_types": ["property-extension"],
            "id": "extension-definition--cb6c6195-ae83-4689-af33-a8f7f63b54cb",
            "modified": "2022-07-06T15:34:22.474326Z",
            "name": "AMA_MITRE",
            "schema": '{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"x_mitre_attack_spec_version": {"type": "string"}, "x_mitre_data_sources": {"type": "array", "items": {"type": "string"}}, "x_mitre_detection": {"type": "string"}, "x_mitre_domains": {"type": "array", "items": {"type": "string"}}, "x_mitre_is_subtechnique": {"type": "boolean"}, "x_mitre_modified_by_ref": {"type": "string"}, "x_mitre_permissions_required": {"type": "array", "items": {"type": "string"}}, "x_mitre_platforms": {"type": "array", "items": {"type": "string"}}, "x_mitre_version": {"type": "string"}, "x_mitre_contributors": {"type": "array", "items": {"type": "string"}}, "x_mitre_system_requirements": {"type": "array", "items": {"type": "string"}}, "x_mitre_defense_bypassed": {"type": "array", "items": {"type": "string"}}, "x_mitre_effective_permissions": {"type": "array", "items": {"type": "string"}}, "x_mitre_impact_type": {"type": "array", "items": {"type": "string"}}, "x_mitre_network_requirements": {"type": "boolean"}, "x_mitre_remote_support": {"type": "boolean"}, "x_mitre_deprecated": {"type": "boolean"}, "x_mitre_old_attack_id": {"type": "string"}, "x_mitre_aliases": {"type": "array", "items": {"type": "string"}}}, "required": ["x_mitre_attack_spec_version", "x_mitre_domains"]}',
            "spec_version": "2.1",
            "type": "extension-definition",
            "version": "1.0",
        },
        "org_props": [
            "x_mitre_attack_spec_version",
            "x_mitre_defense_bypassed",
            "x_mitre_detection",
            "x_mitre_domains",
            "x_mitre_modified_by_ref",
            "x_mitre_platforms",
            "x_mitre_version",
            "x_mitre_data_sources",
            "x_mitre_permissions_required",
            "x_mitre_system_requirements",
            "x_mitre_contributors",
            "x_mitre_deprecated",
            "x_mitre_is_subtechnique",
            "x_mitre_effective_permissions",
            "x_mitre_remote_support",
            "x_mitre_impact_type",
        ],
    },
    "malware_bazaar": {
        "ext": {
            "created": "2023-06-08T16:30:49.442237Z",
            "created_by_ref": "identity--e769b29f-65d2-4cd3-9dbf-aed5609242af",
            "description": "Autogenerated " "extension " "definition",
            "extension_types": ["property-extension"],
            "id": "extension-definition--5084240c-3a33-4931-9dcd-e4b6c5bc1ff3",
            "modified": "2023-06-08T16:30:49.442237Z",
            "name": "AMA_malware_bazaar",
            "schema": "{'$schema': "
            "'http://json-schema.org/schema#', "
            "'type': "
            "'object', "
            "'properties': "
            "{'x_malware_bazaar_tags': "
            "{'type': "
            "'array', "
            "'items': "
            "{'type': "
            "'string'}}}, "
            "'required': "
            "['x_malware_bazaar_tags']}",
            "spec_version": "2.1",
            "type": "extension-definition",
            "version": "1.0",
        },
        "org_props": ["x_malware_bazaar_tags"],
    },
}


staticidentities = {
    "ama_main": {
        "type": "identity",
        "spec_version": "2.1",
        "id": "identity--e769b29f-65d2-4cd3-9dbf-aed5609242af",
        "created": "2022-07-06T17:12:04.766199Z",
        "modified": "2022-07-06T17:12:04.766199Z",
        "name": "AMA_Project",
    }
}
staticextensionidentitymapping = {"mitre": "ama_main", "malware_bazaar": "ama_main"}
